# Generated by Django 5.1 on 2024-11-22 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 10, 39, 9, 559568)),
        ),
    ]
