# Generated by Django 5.1 on 2024-12-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('released_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.BigIntegerField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='brand.brandmodel')),
            ],
        ),
    ]
