# Generated by Django 5.1 on 2024-12-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='established',
            field=models.DateField(),
        ),
    ]
