# Generated by Django 5.1 on 2024-12-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AspireBank', max_length=100)),
                ('is_bankrupt', models.BooleanField(default=False)),
            ],
        ),
    ]
